export const USER_PROPERTIES = [
	{value: "person_id", text: "ID"},
	{value: "first_name", text: "First Name"},
	{value: "middle_name", text: "Middle Name"},
	{value: "last_name", text: "Last Name"},
	{value: "dob", text: "Date of Birth"},
	{value: "apt_num", text: "Apartment Number"},
	{value: "street_name", text: "Street Name"},
	{value: "street_num", text: "Street Number"},
	{value: "city", text: "City"},
	{value: "state", text: "State"},
	{value: "zip", text: "Zip"},
	{value: "country", text: "Country"},
	{value: "country_code", text: "Country Code"},
	{value: "number", text: "Phone Number"},
	{value: "gender", text: "Gender"},
	{value: "e_mail", text: "Email"},
];
